# Generated by Django 4.2.13 on 2024-08-23 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
