# Generated by Django 4.2.13 on 2024-08-08 22:03

from django.db import migrations, models
import libs.truncate_table_mixin


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('image', models.ImageField(blank=True, default='empty_file.png', null=True, upload_to='images', verbose_name='Изображение')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата первой публикации')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'блоги',
            },
            bases=(libs.truncate_table_mixin.TruncateTableMixin, models.Model),
        ),
    ]
