# Generated by Django 4.2.13 on 2024-08-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters_sending', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letterssending',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
    ]
