# Generated by Django 4.2.13 on 2024-08-08 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters_sending', '0002_alter_client_owner_alter_letterssending_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letterssending',
            options={'permissions': [('deactivate_letterssending', 'Выключить рассылку')], 'verbose_name': 'Почтовая рассылка', 'verbose_name_plural': 'почтовые рассылки'},
        ),
    ]
