# Generated by Django 4.2.13 on 2024-08-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters_sending', '0002_letterssending_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letterssending',
            options={'permissions': [('activate_letterssending', 'Активировать')], 'verbose_name': 'Почтовая рассылка', 'verbose_name_plural': 'почтовые рассылки'},
        ),
        migrations.AlterField(
            model_name='letterssending',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
    ]
