# Generated by Django 4.2.13 on 2024-08-09 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters_sending', '0003_alter_letterssending_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('surname', 'name', 'patronym', 'email'), 'permissions': [('view_owner_client', 'Показать своих клиентов')], 'verbose_name': 'Клиент', 'verbose_name_plural': 'клиенты'},
        ),
        migrations.AlterModelOptions(
            name='letterssending',
            options={'permissions': [('deactivate_letterssending', 'Выключить рассылку'), ('view_owner_letterssending', 'Показать свои рассылки')], 'verbose_name': 'Почтовая рассылка', 'verbose_name_plural': 'почтовые рассылки'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('subject',), 'permissions': [('view_owner_message', 'Показать свои сообщения')], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'сообщения'},
        ),
    ]
