# Generated by Django 4.2.13 on 2024-08-09 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters_sending', '0004_alter_client_options_alter_letterssending_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letterssending',
            options={'permissions': [('deactivate_letterssending', 'Выключить рассылку'), ('view_owner_letterssending', 'Показать свои рассылки'), ('stat_owner_letterssending', 'Показать статистику своих рассылок'), ('stat_letterssending', 'Показать статистику рассылков')], 'verbose_name': 'Почтовая рассылка', 'verbose_name_plural': 'почтовые рассылки'},
        ),
    ]
